/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as MultiAngleRouteImport } from './routes/multi-angle'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as BuyerLensRouteImport } from './routes/buyer-lens'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'

const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiAngleRoute = MultiAngleRouteImport.update({
  id: '/multi-angle',
  path: '/multi-angle',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerLensRoute = BuyerLensRouteImport.update({
  id: '/buyer-lens',
  path: '/buyer-lens',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/buyer-lens': typeof BuyerLensRoute
  '/clips': typeof ClipsRoute
  '/multi-angle': typeof MultiAngleRoute
  '/players': typeof PlayersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/buyer-lens': typeof BuyerLensRoute
  '/clips': typeof ClipsRoute
  '/multi-angle': typeof MultiAngleRoute
  '/players': typeof PlayersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/buyer-lens': typeof BuyerLensRoute
  '/clips': typeof ClipsRoute
  '/multi-angle': typeof MultiAngleRoute
  '/players': typeof PlayersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/buyer-lens'
    | '/clips'
    | '/multi-angle'
    | '/players'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brands' | '/buyer-lens' | '/clips' | '/multi-angle' | '/players'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/buyer-lens'
    | '/clips'
    | '/multi-angle'
    | '/players'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  BuyerLensRoute: typeof BuyerLensRoute
  ClipsRoute: typeof ClipsRoute
  MultiAngleRoute: typeof MultiAngleRoute
  PlayersRoute: typeof PlayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-angle': {
      id: '/multi-angle'
      path: '/multi-angle'
      fullPath: '/multi-angle'
      preLoaderRoute: typeof MultiAngleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-lens': {
      id: '/buyer-lens'
      path: '/buyer-lens'
      fullPath: '/buyer-lens'
      preLoaderRoute: typeof BuyerLensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  BuyerLensRoute: BuyerLensRoute,
  ClipsRoute: ClipsRoute,
  MultiAngleRoute: MultiAngleRoute,
  PlayersRoute: PlayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
