/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SampleDataRouteImport } from './routes/sample-data'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as MultiAngleRouteImport } from './routes/multi-angle'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as BuyerLensRouteImport } from './routes/buyer-lens'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntelligenceBrandRouteImport } from './routes/intelligence.$brand'

const SampleDataRoute = SampleDataRouteImport.update({
  id: '/sample-data',
  path: '/sample-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiAngleRoute = MultiAngleRouteImport.update({
  id: '/multi-angle',
  path: '/multi-angle',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerLensRoute = BuyerLensRouteImport.update({
  id: '/buyer-lens',
  path: '/buyer-lens',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceBrandRoute = IntelligenceBrandRouteImport.update({
  id: '/intelligence/$brand',
  path: '/intelligence/$brand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/buyer-lens': typeof BuyerLensRoute
  '/clips': typeof ClipsRoute
  '/dashboard': typeof DashboardRoute
  '/highlights': typeof HighlightsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/multi-angle': typeof MultiAngleRoute
  '/players': typeof PlayersRoute
  '/sample-data': typeof SampleDataRoute
  '/intelligence/$brand': typeof IntelligenceBrandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/buyer-lens': typeof BuyerLensRoute
  '/clips': typeof ClipsRoute
  '/dashboard': typeof DashboardRoute
  '/highlights': typeof HighlightsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/multi-angle': typeof MultiAngleRoute
  '/players': typeof PlayersRoute
  '/sample-data': typeof SampleDataRoute
  '/intelligence/$brand': typeof IntelligenceBrandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/buyer-lens': typeof BuyerLensRoute
  '/clips': typeof ClipsRoute
  '/dashboard': typeof DashboardRoute
  '/highlights': typeof HighlightsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/multi-angle': typeof MultiAngleRoute
  '/players': typeof PlayersRoute
  '/sample-data': typeof SampleDataRoute
  '/intelligence/$brand': typeof IntelligenceBrandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/buyer-lens'
    | '/clips'
    | '/dashboard'
    | '/highlights'
    | '/login'
    | '/marketplace'
    | '/multi-angle'
    | '/players'
    | '/sample-data'
    | '/intelligence/$brand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/buyer-lens'
    | '/clips'
    | '/dashboard'
    | '/highlights'
    | '/login'
    | '/marketplace'
    | '/multi-angle'
    | '/players'
    | '/sample-data'
    | '/intelligence/$brand'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/buyer-lens'
    | '/clips'
    | '/dashboard'
    | '/highlights'
    | '/login'
    | '/marketplace'
    | '/multi-angle'
    | '/players'
    | '/sample-data'
    | '/intelligence/$brand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  BuyerLensRoute: typeof BuyerLensRoute
  ClipsRoute: typeof ClipsRoute
  DashboardRoute: typeof DashboardRoute
  HighlightsRoute: typeof HighlightsRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MultiAngleRoute: typeof MultiAngleRoute
  PlayersRoute: typeof PlayersRoute
  SampleDataRoute: typeof SampleDataRoute
  IntelligenceBrandRoute: typeof IntelligenceBrandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample-data': {
      id: '/sample-data'
      path: '/sample-data'
      fullPath: '/sample-data'
      preLoaderRoute: typeof SampleDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-angle': {
      id: '/multi-angle'
      path: '/multi-angle'
      fullPath: '/multi-angle'
      preLoaderRoute: typeof MultiAngleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-lens': {
      id: '/buyer-lens'
      path: '/buyer-lens'
      fullPath: '/buyer-lens'
      preLoaderRoute: typeof BuyerLensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/$brand': {
      id: '/intelligence/$brand'
      path: '/intelligence/$brand'
      fullPath: '/intelligence/$brand'
      preLoaderRoute: typeof IntelligenceBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  BuyerLensRoute: BuyerLensRoute,
  ClipsRoute: ClipsRoute,
  DashboardRoute: DashboardRoute,
  HighlightsRoute: HighlightsRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MultiAngleRoute: MultiAngleRoute,
  PlayersRoute: PlayersRoute,
  SampleDataRoute: SampleDataRoute,
  IntelligenceBrandRoute: IntelligenceBrandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
